- tests/test_tools.py
The same PR as #36 but into `master`.
> v12: debian/changelog and setup.py versions are same

- cocaine/proxy/proxy.py
application name (key) from the cache if the cache list is empty.
> proxy: clean the cache pool of applications and remove

- cocaine/proxy/proxy.py
The proxy treats a reply from an app depending on `X-Cocaine-HTTP-Proto-Version` header presence and value. Value `1.1` makes proxy treat an empty body chunk (length 0) as
the end of reply. In case of `1.0` or absence of the header the proxy reads until
closing Cocaine-Stream.
The motivation is to allow applications to send replies to users as soon as possible and to hold Cocaine Tx stream at the same time. Apps can do any asynchronous (from the user's point of view) job.
Keeping a Tx stream is needed to properly counting of current load of a worker.
> feat(proxy): Extend HTTP reply protocol

- cocaine/proxy/mds_exec.py
- cocaine/tools/version.py
> MDS plugin features

- cocaine/tools/actions/logging.py
- cocaine/tools/cli.py
- cocaine/tools/dispatcher.py
- cocaine/tools/version.py
- debian/changelog
Support for controlling new logging service via cocaine-tools
> feat(): add support for new logging service

- cocaine/proxy/mds_direct.py
- cocaine/proxy/proxy.py
> feat(proxy): add mds_direct plugin for direct access of mds cloud.

- cocaine/proxy/mds_direct.py
- cocaine/tools/version.py
- debian/changelog
> fix(): add forgotten routing group to mds_direct

- cocaine/proxy/mds_direct.py
- cocaine/tools/version.py
- debian/changelog
> fix - do not change iterable in loop

- cocaine/tools/cli.py
> fix(): notify user about IO errors(e.g. - no such file error)

- cocaine/proxy/mds_direct.py
- cocaine/tools/version.py
- debian/changelog
> Allow mds keys

- cocaine/tools/actions/__init__.py
- cocaine/tools/actions/auth.py
- cocaine/tools/cli.py
- cocaine/tools/dispatch.py
- cocaine/tools/interactive/__init__.py
- cocaine/tools/version.py
- debian/changelog
This commit adds authorization specific tools.
> feat: auth management

- cocaine/proxy/proxy.py
It is useful to have resulting name of cocaine application in http headers.
If you think that my pull request is too stupid, not enough pythonic or whatever else, just reject and forget about it. :)
> return cocaine application name in http header X-Cocaine-Application

- cocaine/tools/dispatch.py
- cocaine/tools/version.py
- debian/changelog
- debian/control
- requirements.txt
This commit allows to configure both system- and user-wide Locator
options, like host and port.
Replaces #86.
> feat: configurable locator options

- cocaine/tools/actions/access.py
- cocaine/tools/cli.py
- cocaine/tools/dispatch.py
- debian/changelog
> feat: add access-control tools

- cocaine/tools/actions/auth.py
> fix: update members on token change

- cocaine/proxy/mds_direct.py
- cocaine/proxy/proxy.py
Add srw application last chance to process invocation from common pool
@noxiouz PTAL
> feat: add srw application last chance to process invocation 

- cocaine/tools/actions/logs.py
Adaption bound to https://github.com/3Hren/cocaine-plugins/pull/121
> refact: adapt to new logging protocol, better description

- cocaine/tools/version.py
- debian/changelog
> version: bump - 0.12.13.0

- cocaine/proxy/mds_direct.py
- cocaine/proxy/proxy.py
- cocaine/tools/version.py
- debian/changelog
@3Hren @noxiouz @borislitv PTAL
> fix: use tracing logic in mds_direct

- cocaine/tools/actions/access/edit.py
- cocaine/tools/cli.py
- cocaine/tools/dispatch.py
'access:grant/revoke' command line options
**Merge ready**
@3Hren, @antmat PTAL
> feat(access): service based ACL edit commands

- cocaine/tools/dispatch.py
Use secure service for 'unicat'.
> fix: use secure service

- cocaine/tools/actions/unicorn.py
- cocaine/tools/cli.py
- cocaine/tools/dispatch.py
- cocaine/tools/version.py
- debian/changelog
Required to be able to configure things for https://github.com/3Hren/cocaine-http-proxy/issues/20 and tracing.
> feat: add unicorn edit tool

- cocaine/proxy/proxy.py
- cocaine/tools/version.py
- debian/changelog
Optionally proxy http headers as cocaine headers.
@noxiouz PTAL
> feat: map headers to cocaine

- cocaine/tools/actions/common.py
- cocaine/tools/cli.py
- cocaine/tools/dispatch.py
- cocaine/tools/version.py
- debian/changelog
bound to https://github.com/3Hren/cocaine-core/pull/199/files and https://github.com/cocaine/cocaine-framework-python/pull/72
> Uuid support
